### ISSUE TITLE
Use Google's (reverse) image search to get more dog images

### ISSUE THREAD

**Issue by SvenDH** [KDercksen/hunter2_dbi#15]
Maybe we could also use Googles image search API on our hard to predict doggos. This requires us to find the classes that are hard to predict and use the label as a query. Another option is to use a representative image for reverse image search. The last option could be quite challenging but this code snippet could be a helpful start:

```python
import requests

filePath = '/data/train/doggo.png'
searchUrl = 'http://www.google.hr/searchbyimage/upload'
multipart = {'encoded_image': (filePath, open(filePath, 'rb')), 'image_content': ''}
response = requests.post(searchUrl, files=multipart, allow_redirects=False)
fetchUrl = response.headers['Location']
```

To get the images we can use the [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) library to process the response of Google's API.

**Comment by KDercksen** [comment]
Fun idea :smile:

Finding a representative image is as hard as you make it... You could calculate the centroid of all the feature vectors for a certain class and use the image closest to the centroid as the representative, for example.

**Comment by stephandooper** [comment]
Most of the API's I found are deprecated by google. I have tried GoogleScraper and serpscrap, but could not get them to work. 
As a workaround I found this script that downloads the top N images on a search result. It is currently capped at 100 images I think, but more than enough for our current example. 

TODO:
The way I see it is that I can adjust it to download images for search results specified in a text file and download them to specific directories labelled with the dog breed name .

At this point, we have to copy the file name id's and add them ot the csv label.

Possible problem: 
there are most certainly going to be duplicate images/file names with respect to the current data set. 
Still trying to figure out a workaround for this.

 https://gist.github.com/genekogan/ebd77196e4bf0705db51f86431099e57

**Comment by KDercksen** [comment]
As far as renaming files and generating image IDs, see `shutil` and `uuid` modules!

**Comment by stephandooper** [comment]
The Ids have already been made (they are simply the file names), they have to be added to the csv though.
As for the remaining time, I suggest we simply hand-pick a list of dogs that were hard to classify and download them.

**Comment by KDercksen** [comment]
You talked about duplicate filenames; generating new filenames would be a workaround for that, I meant. Handpicking a list of breeds sounds fine to me
